### ISSUE TITLE
LGPL better for commercial products

### ISSUE THREAD

**Issue by dalers** [FxDev/PetitModbus#1]
First, thank you very much for Petit Modbus! I understand commercial use is allowed from the reply "You can use it in your commercial project" made March 6, 2019 to a comment on http://www.firatdeveci.com/petit-modbus-kucuk-ama-dev/.

However, it is difficult for a commercial project to also be licensed by the GPL (which is one of the purposes of the GPL). Was your intent to require only that changes to Petit Modbus also be licensed under the GPL? If so, then the Lesser GPL (e.g. LGPLv3) would be more appropriate and allow greater use of Petit Modbus. The license should also be mentioned specifically in readme.md, and not inferred by the content of the included LICENSE file (and "It's free to use for non-commercial projects" removed from readme.md, perhaps replaced with "Donations gratefully accepted" ;-) ).

**Comment by FxDev** [comment]
Thanks, I replaced it.
Of course it's not free for commercial projects. I removed comments in my web site too.
