### ISSUE TITLE
Great work, little problem in error responses.

### ISSUE THREAD

**Issue by mnabarro** [FxDev/PetitModbus#2]
Hi! I'm working in a modbus slave with stm32. I managed to make your code work with my development board (STM32F072) Nucleo-64. 
It's working OK, except for exception codes response.

I followed the example at http://www.simplymodbus.ca/exceptions.htm and get the next:

_ Request

This command is requesting the ON/OFF status of discrete coil #1186
from the slave device with address 10. _

**0A 01 04A1 0001 AC63**

Response, should be 
**0A 81 02 B053** 

but, actually is:
 **0A 81 C7 70**

That is detected as "corrupted frame error" by Modlink Vcl demo.
I know that software package is working very well with different hardware.

I'll try to fix the error response assembling. In any case, I'll send you the project for stm32+HAL, to share with other people.

Thanks a lot for your work. Regards

Matias.

**Comment by FxDev** [comment]
Thank you for your comment.
Yes this is known issue. If you share the modbus codes with me, I can fix that problem.

**Comment by mnabarro** [comment]
> Thank you for your comment.
> Yes this is known issue. If you share the modbus codes with me, I can fix that problem.

Hi! I'm attaching my project with faulty response. Best regards.

[F072RB_MODBUS.zip](https://github.com/FxDev/PetitModbus/files/5705721/F072RB_MODBUS.zip)

**Comment by FxDev** [comment]
Thank you so much, I will change it in few days.

**Comment by sealj553** [comment]
The issue is that `HandlePetitModbusError` doesn't write the exception code correctly. Changing it to the following should work (update header and calls to add the function code):
```
void HandlePetitModbusError(unsigned char Function, char ErrorCode){
    Petit_Tx_Data.Function    = Function | 0x80;
    Petit_Tx_Data.Address     = PETITMODBUS_SLAVE_ADDRESS;
    Petit_Tx_Data.DataLen     = 1;
    Petit_Tx_Data.DataBuf[0]  = ErrorCode;
    PetitSendMessage();
}
```

**Comment by aniedworok** [comment]
Hello! I also receive the the same problem with exception code response. 
Kind regards and happy New Year:-)
Andrew

**Comment by FxDev** [comment]
Thank you all!
Now PetitModbus Ver1.1 is online!

Error messages problem is solved.

**Comment by FxDev** [comment]
> The issue is that `HandlePetitModbusError` doesn't write the exception code correctly. Changing it to the following should work (update header and calls to add the function code):
> 
> ```
> void HandlePetitModbusError(unsigned char Function, char ErrorCode){
>     Petit_Tx_Data.Function    = Function | 0x80;
>     Petit_Tx_Data.Address     = PETITMODBUS_SLAVE_ADDRESS;
>     Petit_Tx_Data.DataLen     = 1;
>     Petit_Tx_Data.DataBuf[0]  = ErrorCode;
>     PetitSendMessage();
> }
> ```

**Comment by phantom1299** [comment]
There is still a bug while handling modbus exceptions. According to the modbus specification V1.1b chapter 7 MODBUS Exception Responses:

> Function Code Field: In a normal response, the server echoes the function code of the
original request in the function code field of the response. All function codes have a most–
significant bit (MSB) of 0 (their values are all below 80 hexadecimal). In an exception
response, the server sets the MSB of the function code to 1. This makes the function code
value in an exception response exactly 80 hexadecimal higher than the value would be for a
normal response.

So the `HandlePetitModbusError` function should be:
```
void HandlePetitModbusError(char ErrorCode)
{
    // Initialise the output buffer. The first byte in the buffer says how many registers we have read
    Petit_Tx_Data.Function    = Petit_Rx_Data.Function | 0x80;  // <<< This line
    Petit_Tx_Data.Address     = PETITMODBUS_SLAVE_ADDRESS;
    Petit_Tx_Data.DataLen     = 1;
    Petit_Tx_Data.DataBuf[0]  = ErrorCode;
    PetitSendMessage();
}
```

As @sealj553 pointed out in his solution.

**Comment by FxDev** [comment]
Thank you. I fixed it! :)
